services: 
  wordpress:
    image: wordpress
    links:
      - db:mysql
    expose:
      - 80
    environment:
      - "VIRTUAL_HOST=wordpress.zairecloud.pt"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=wordpress.zairecloud.pt"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
