version: '3'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    links:
      - db:mysql
    expose:
      - 81
    environment:
      - "VIRTUAL_HOST=wordpress.zairecloud.pt"
      - "VIRTUAL_PORT=81"
      - "LETSENCRYPT_HOST=wordpress.zairecloud.pt"
    networks:
      - nginx-proxy_network
    restart: unless-stopped
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: unless-stopped
      
networks:
  nginx-proxy_network:
    external: true