- name: Deployment
  uses: TapTap21/docker-remote-deployment-action@v1.0
  with:
    remote_docker_host: ${{ secrets.RADEON_SSH_HOST }}
    ssh_private_key: ${{ secrets.RADEON_SSH_PRIVATE_KEY }}
    ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
    stack_file_name: docker-compose.yml
    args: -p hello-world up -d
